version: "3.9"
services:
  postgresql:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always
    networks:
      - default-network

  backend:
    image: mybackend:latest
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    networks:
      - default-network
    volumes:
      - ./server/media:/project/media
    env_file:
      - ./server/.env
    depends_on:
      - postgresql
    expose:
      - 8000
    restart: always
  
  frontend:
    image: myfrontend:latest 
    networks:
      - default-network
    expose:
      - 3000
    restart: always
  
  nginx:
    build:
      context: ./nginx
    networks:
      - default-network
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./server/static:/project/static
    restart: always

networks:
  default-network:
